### ISSUE TITLE
# 로그인 시에만 접속 가능한 라우터 설계

### ISSUE THREAD

**Issue by RookieAND** [RookieAND/KUAGORA#16]
## Topic
로그인 시에만 접속 가능한 라우터 설계

## Desc

- 요청 헤더에 엑세스 토큰이 존재할 때만 라우터를 통과할 수 있도록 해야 함.
- 만약 헤더에 토큰이 없거나 유효하지 않은 토큰일 경우, 리프레쉬 토큰을 요청하도록 해야 함.
- 리프레시 토큰 또한 유효하지 않을 경우, 클라이언트 단위에서 로그아웃을 진행하도록 해야 함.

## TODO

- [x] 요청 헤더에 엑세스 토큰이 존재할 때만 라우터를 통과시키는 미들웨어 제작
- [x] Authorization 헤더에 토큰이 없을 경우, 리프레시 토큰을 요구하는 로직 제작
- [x] axios 인스턴스의 인터셉터에서, 리프레시 토큰의 요구를 자동으로 캐치하도록 로직 설계
- [x] 리프레시 토큰이 유효하지 않을 경우, 자동으로 로그아웃을 진행하는 로직 구현.
