### ISSUE TITLE
# JWT 토큰 발급, Social 로그인 구현

### ISSUE THREAD

**Issue by RookieAND** [RookieAND/KUAGORA#2]
## Topic
JWT 토큰 발급, Social 로그인 구현

## Desc

- jwt 토큰을 발급하고, 유효성 검사를 진행하는 인증 모듈 필요.
- 소셜 플랫폼에서 로그인이 완료되었을 경우, 인계받은 토큰을 전달하는 모듈 필요.
- Kakao, Google, Naver 소셜 로그인 모듈을 구현하고, 정상 작동을 확인.

## TODO

- [x]  소셜 로그인 페이지 레이아웃 및 기능 구현
- [x]  JWT 토큰 발급 / 유효성 검사 모듈
- [x]  신규 회원가입 진행 전, Column 유효성 검사 확인
- [x]  토큰의 유효성이 결격되었을 경우, 로그아웃 진행
