### ISSUE TITLE
# 서버 및 클라이언트 API 타입 재정의

### ISSUE THREAD

**Issue by RookieAND** [RookieAND/KUAGORA#29]
## Topic
클라이언트 및 서버에서 사용하는 API 와 관련된 타입 재정의 필요

## Desc

현재 클라이언트 측에서 사용되는 API들이 너무 난잡하고, 타입의 재사용성이 크게 떨어짐
따라서 이를 해결하기 위해 서버에서 제공되는 데이터의 양식을 맞춰 타입을 재정의해야 함
클래스 상속을 통해 공통된 부분은 통일 시키되, 각기 다른 분야의 인터페이스는 독립적으로 설계

## TODO

- [x] 질문, 검색, 댓글, 좋아요, 키워드로 API 문서를 세분화하고 함수명 재정의
- [x] 상호 연관된 타입은 상속을 통해 확장성을 보장하여 정의하고, 최대한 간결하게 정의
- [x] 서버 내에서 사용되는 컨트롤러 또한 각 파트에 맞게 세분화
