### ISSUE TITLE
# 메인 페이지 레이아웃 구조 변경

### ISSUE THREAD

**Issue by RookieAND** [RookieAND/KUAGORA#32]
## Topic
메인 페이지의 레이아웃 구성을 유저 친화적으로 재구성

## Desc

메인 페이지에 유저들이 가장 최근에 올린 글 및 인기 있는 글을 각각 8개 정도 추려서 보여주는 섹션 추가.
사이트 정보를 보여주는 컴포넌트의 경우 메인 페이지 하단에 넣음으로서 후순위로 보이도록 수정해야 함.

## TODO

- [x] 유저들이 가장 최근에 업로드한 글 8개를 선별하여 보여주는 레이아웃 추가
- [x] 유저들이 가장 좋아요를 많이 누른 글 8개를 선별하여 보여주는 레이아웃 추가
- [x] 사이트 정보 컴포넌트의 존속 여부를 결정하고, 이를 제거할지 아래로 내릴지 결정
- [x] "지금 질문하기" 버튼 클릭 시, 질문글 작성 페이지로 이동하도록 수정. (비로그인 시 로그인 이동)
