### ISSUE TITLE
# 질문글 검색 바를 독립적인 레이아웃으로 재설계

### ISSUE THREAD

**Issue by RookieAND** [RookieAND/KUAGORA#35]
## Topic
질문글 검색 바와 관련된 컴포넌트를 독립적인 레이아웃으로 설계해야 함.

## Desc

현재 질문글의 경우 각 페이지 내의 state에 종속적인 형태를 취하고 있어 수정이 어려움.
따라서 검색 바 섹션의 경우 별도의 템플릿 혹은 컴포넌트 폴더로 분류하고 관련 로직을 몰아 넣아야 함.
또한 질문글, 검색 결과 페이지에서 검색 바를 기존보다 가시성을 더 좋게 배치해야 할 필요성이 있음.

## TODO

- [x] 검색 바를 독립적인 Organism으로 분류하고, 관련 로직 또한 내부에 밀집시켜야 함.
- [x] 페이지에 종속적이었던 검색 value State를 독립적으로 작동하도록 관련 로직을 리팩터링.
- [x] 검색 옵션의 경우 키워드 별 / 제목 별 로만 두고, 그 외 옵션은 결과 페이지에서 필터링하도록 수정.
