### ISSUE TITLE
# Husky 라이브러리를 추가하여 컨벤션 체크 자동화.

### ISSUE THREAD

**Issue by RookieAND** [RookieAND/KUAGORA#42]
## Topic
Husky, commitlint, lint-staged로 lint 작업과 commit convention 체크 자동화

## Desc

ESLint와 commitlint를 돌려, 기준에 미달되었을 경우 commit을 거부하도록 해보자.
Husky 라이브러리를 적극 활용하여 git hooks에 대한 기초적인 사용법을 익혀보자.

## TODO

- [x] Husky 라이브러리 추가 및 관련 설정 완료
- [x] commitlint, lint-staged 라이브러리 추가 및 config 파일 작성
- [x] code / commit convention 위반 시 commit이 막히는지 테스트
