### ISSUE TITLE
# React Portal 및 모달, 알림 기능 추가

### ISSUE THREAD

**Issue by RookieAND** [RookieAND/KUAGORA#49]
## Topic
# React Portal 및 모달, 알림 기능 추가

## Desc

- WebSocket 연동 실시간 알림과 Modal에 사용할 React Portal을 각각 추가하고, 공통된 스타일을 입힌다.
- 실시간 알림의 경우 페이지 우상단, 우하단 두 곳에 알림을 띄우도록 유도한다.
- Modal의 경우 배경을 반투명한 검은색으로 입히고, 내부의 규격을 일정하게 맞추어 지정한다.

## TODO

- [x] 새로운 글을 작성하고 이를 등록하기 전, 최종 확인을 요하는 Modal 설계
- [x] 새로운 댓글을 작성하고 이를 등록하기 전, 최종 확인을 요하는 Modal 설계
- [x] 내가 작성한 답글 채택 시 알림을 화면 우상단에 띄우도록 설계
- [x] 내가 작성한 댓글을 삭제할 시 알림을 화면 우상단에 띄우도록 설계
- [x] 두 개의 React Portal 추가 및 관련 Hook 설계
