### ISSUE TITLE
# 클라이언트 내 API 유틸 함수 제작

### ISSUE THREAD

**Issue by RookieAND** [RookieAND/KUAGORA#7]
## Topic
클라이언트 내 자체적인 API 유틸 함수 제작

## Desc

서버와 클라이언트 간의 HTTP 통신을 수행할 API 함수를 제작해야 한다.
GET, POST, DELETE, PATCH (UPDATE) 네 개의 케이스에 대한 유틸 함수를 제작한다.
추가적으로 Axios 인스턴스를 설정하여 BaseURL, AxiosResponse를 핸들링하고 결과를 전처리하여 가공한다.

## TODO

- [x] get, post, patch, delete HTTP 통신을 진행하는 API 유틸 함수 설계
- [x] API 통신 결과로 받는 에러 및 결과 데이터에 대한 전처리 과정 수행
- [x] 전역적으로 사용할 axios 인스턴스를 만들고, 인터셉터 설정 진행.
