### ISSUE TITLE
# 메인 및 로그인 페이지 레이아웃 디자인 및 제작

### ISSUE THREAD

**Issue by RookieAND** [RookieAND/KUAGORA#8]
## Topic
메인 페이지 및 로그인 페이지 디자인 및 제작

## Desc

- 메인 페이지 레이아웃과 로그인 페이지 레이아웃을 Figma로 제작해야 함.
- 제작된 레이아웃을 style 파일에 개별적으로 작성하여 사용이 용이하도록 해야 함.
- 소셜 로그인 구현을 진행하고, 이를 로그인 페이지에서 사용 가능하도록 설정해야 함.

## TODO

- [x]  메인 페이지 레이아웃과 로그인 페이지 레이아웃을 css로 구현
- [x]  제작된 레이아웃을 CSS로 치환하여 각 컴포넌트 별 style 파일 작성
- [x] 상단 네비게이션 바를 추가한 후, 로그인 페이지 라우팅 작업 진행.
